version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tickets
  events:
    image: events-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8081:8081"
  registration:
    image: registration-service:0.0.1-SNAPSHOT
    depends_on:
      - mongo
      - events
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8082:8082"
