version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tickets